"use client";

import { ChevronDown } from "lucide-react";
import { useState } from "react";
import { useIntersectionObserver } from "~/hooks/use-intersection-observer";

const faqs = [
  {
    question: "Does this work with any YouTube video?",
    answer:
      "It works with any YouTube video that has captions enabled, whether manually uploaded or auto-generated by YouTube. If a video has transcripts disabled, we'll let you know.",
  },
  {
    question: "How many languages are supported?",
    answer:
      "We support all languages available on YouTube, which includes 100+ languages. The app detects all available languages and lets you switch between them instantly without re-fetching.",
  },
  {
    question: "Is there a rate limit or usage cap?",
    answer:
      "When self-hosting, there are no artificial limits. YouTube may rate-limit requests from server IPs at high volume. For production use, we recommend configuring the optional Oxylabs residential proxy.",
  },
  {
    question: "What export formats are available?",
    answer:
      "You can export transcripts as plain text (TXT), formatted PDF documents, or structured JSON with metadata. All formats include the full transcript text and video information.",
  },
  {
    question: "Do I need an API key or account?",
    answer:
      "No. This tool is completely free and requires no accounts, API keys, or subscriptions. Just clone the repo, run Docker Compose, and start extracting transcripts.",
  },
  {
    question: "How is this different from other transcript tools?",
    answer:
      "It's fully self-hosted and open-source. Your data stays on your infrastructure. There's no tracking, no ads, no usage limits, and no vendor lock-in. Plus, all languages are cached locally for instant switching.",
  },
];

export function FAQSection() {
  const { ref, isInView } = useIntersectionObserver({ margin: "-100px" });
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section
      id="faq"
      ref={ref}
      className="relative bg-gray-50 py-20 dark:bg-gray-900"
      style={{ fontFamily: "var(--font-outfit)" }}
    >
      <div className="relative z-10 container mx-auto px-6">
        {/* Header */}
        <div
          className={`reveal mb-12 text-center ${isInView ? "in-view" : ""}`}
        >
          <h2 className="mb-4 text-4xl font-bold text-gray-900 md:text-5xl dark:text-white">
            Frequently Asked{" "}
            <span className="bg-gradient-to-r from-[#459F94] to-[#EDB118] bg-clip-text text-transparent">
              Questions
            </span>
          </h2>
          <p className="mx-auto max-w-2xl text-lg text-gray-600 dark:text-gray-400">
            Everything you need to know about the YouTube Transcript Extractor.
          </p>
        </div>

        {/* FAQ Grid */}
        <div className="mx-auto grid max-w-4xl grid-cols-1 gap-4 md:grid-cols-2 md:gap-6">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className={`reveal rounded-2xl bg-white p-6 shadow-sm transition-all dark:bg-gray-800 ${
                index >= 4 ? "md:col-span-2" : ""
              } ${isInView ? "in-view" : ""}`}
              style={
                { "--stagger": `${index * 0.1}s` } as React.CSSProperties
              }
            >
              <button
                onClick={() =>
                  setOpenIndex(openIndex === index ? null : index)
                }
                className="flex w-full cursor-pointer items-start justify-between gap-4 text-left"
              >
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                  {faq.question}
                </h3>
                <ChevronDown
                  className={`h-5 w-5 flex-shrink-0 text-[#459F94] transition-transform ${
                    openIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>
              <div
                className={`overflow-hidden transition-all duration-300 ${
                  openIndex === index
                    ? "mt-4 max-h-96 opacity-100"
                    : "max-h-0 opacity-0"
                }`}
              >
                <p className="text-gray-600 dark:text-gray-400">{faq.answer}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
